### ISSUE TITLE
Remove redundant config params

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomox-sdk#87]
Remove:
```
deposit:
  tomochain:
    distribution_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    issuer_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    lock_unix_timestamp: 0
    signer_private_key: 0x3411b45169aa5a8312e51357db68621031020dcf46011d7431db1bbb6d3922ce
    starting_balance: 100
    token_asset_code: WETH
```

Change:
```
ethereum:
```
To:
```
tomochain:
```
